FROM python:3.11-slim

WORKDIR /app

COPY backend/ /app

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

RUN apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev

RUN pip install --no-cache-dir -r requirements.txt

CMD ["/wait-for-it.sh", "mysql:3306", "-t", "60", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]